# Do not change this
config-version: 2

# Set disable-tps to -1 to disable
# Set cooldown to -1 to disable
# %time% placeholder for cooldown
elytra:
  disable-tps: 17
  unequip: false
  no-sprint: true
  rocket-cooldown: 15
  cooldown-message: '&cPlease wait &4%time% &cseconds before using this again'

# Set disable-tps to -1 to disable
redstone:
  disable-tps: 13

# Find ignore values at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
# Nospawns will disable all spawns default false
mobs:
  spawn-chance:
    ignore:
      - BUILD_IRONGOLEM
      - BUILD_SNOWMAN
      - BUILD_WITHER
      - BREEDING
    nospawns: false
    20: 100
    19: 75
    18: 50
    17: 35
    16: 25
    15: 15
    14: 10
    13: 5
    12: 0
    11: 0
    10: 0
    9: 0
    8: 0
    7: 0
    6: 0
    5: 0
    4: 0
    3: 0
    2: 0
    1: 0
    0: 0

