name: ToastsAntiCrash
version: @version@
main: net.cb2k.toastsanticrash.Main
commands:
  anticrash:
    description: Anti crash reload command
    usage: /anticrash
  allowcreative:
    description: Allow player to use creative
    usage: /allowcreative